services:
  db:
    image: postgres:15-alpine
    container_name: jobzmitra-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Ani#@123"
      POSTGRES_DB: jobzmitradb

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d jobzmitradb"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: jobzmitra-backend

    environment:
      DATABASE_URL: "postgresql://postgres:Ani%23%40123@db:5432/jobzmitradb"

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8000:8000"

    volumes:
      - ./backend/uploads:/app/uploads

    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: jobzmitra-frontend

    depends_on:
      - backend

    environment:
      BACKEND_URL: "http://backend:8000"

    ports:
      - "3000:3000"

    restart: unless-stopped


volumes:
  postgres_data: