"""Add media attachments

Revision ID: 3e7009796ef6
Revises: 63657169388a
Create Date: 2026-06-23 20:57:51.226933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e7009796ef6'
down_revision: Union[str, Sequence[str], None] = '63657169388a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('media_attachments', sa.JSON(), nullable=True))
    op.drop_column('posts', 'media_type')
    op.drop_column('posts', 'media_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('media_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('media_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'media_attachments')
    # ### end Alembic commands ###
