"""add reel comments

Revision ID: 4f02d37b5bf4
Revises: d1b1aab5e490
Create Date: 2026-06-25 23:01:58.917298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f02d37b5bf4'
down_revision: Union[str, Sequence[str], None] = 'd1b1aab5e490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reel_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reel_comments_id'), 'reel_comments', ['id'], unique=False)
    op.add_column('reels', sa.Column('comments_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reels', 'comments_count')
    op.drop_index(op.f('ix_reel_comments_id'), table_name='reel_comments')
    op.drop_table('reel_comments')
    # ### end Alembic commands ###
