"""add points and badges

Revision ID: e0c4cd3c3a1b
Revises: 850bee85fcb5
Create Date: 2026-06-25 20:19:36.078131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c4cd3c3a1b'
down_revision: Union[str, Sequence[str], None] = '850bee85fcb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('badges', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'badges')
    op.drop_column('users', 'points')
    # ### end Alembic commands ###
